version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env
    depends_on:
      - ollama

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: rebuild
          path: ./frontend/package.json

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    env_file:
      - .env

volumes:
  ollama:
