version: '3.8'

services:
  frontend:
    image: ghcr.io/akdavid/ollama_miniapp/ollama_miniapp-frontend:latest
    ports:
      - '80:80'
    depends_on:
      - backend

  backend:
    image: ghcr.io/akdavid/ollama_miniapp/ollama_miniapp-backend:latest
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - ENV=production

  ollama:
    image: ghcr.io/akdavid/ollama_miniapp/ollama_miniapp-ollama:latest
    ports:
      - '11434:11434'
    env_file:
      - .env
    environment:
      - OLLAMA_DEBUG=false
