services:
  frontend:
    build:
      context: ./frontend
      target: ${NODE_ENV:-development} # Utilise "development" par défaut
    ports:
      - '8080:5173' # Dev server
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .env
    environment:
      - ENV=development

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile.ollama.dev
    ports:
      - '11434:11434'
    volumes:
      - ollama:/root/.ollama
    entrypoint: /entrypoint.sh
    env_file:
      - .env
    environment:
      - OLLAMA_DEBUG=true
      - OLLAMA_MAX_LOADED_MODELS=1

volumes:
  ollama:
