FROM ollama:latest

# Étape de build pour Ollama
FROM ollama/ollama:latest

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Copier le script d'entrée dans le conteneur
COPY entrypoint.sh /entrypoint.sh

# Ajouter les droits d'exécution au script
RUN chmod +x /entrypoint.sh

# Définir le script comme point d'entrée
ENTRYPOINT ["/entrypoint.sh"]
