name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read
  packages: write

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=./backend pytest backend/tests

  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/develop' # Exécuter uniquement sur develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build --no-cache -t ollama_miniapp-backend ./backend

  build-frontend:
    name: Build Frontend Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/develop' # Exécuter uniquement sur develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build --no-cache -t ollama_miniapp-frontend ./frontend

  build-ollama:
    name: Build Custom Ollama Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/develop' # Exécuter uniquement sur develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Ollama Docker Image
        run: |
          docker build -f Dockerfile.dev --no-cache -t ollama_miniapp-ollama ./ollama

  build-and-push-backend:
    name: Build and Push Backend Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/master' # Exécuter uniquement sur master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Backend Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/ollama_miniapp-backend:latest ./backend
          docker push ghcr.io/${{ github.repository }}/ollama_miniapp-backend:latest

  build-and-push-frontend:
    name: Build and Push Frontend Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/master' # Exécuter uniquement sur master
    if: github.ref == 'refs/heads/master' # Exécuter uniquement sur master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Frontend Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/ollama_miniapp-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository }}/ollama_miniapp-frontend:latest

  build-and-push-ollama:
    name: Build and Push Custom Ollama Docker Image
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/master' # Exécuter uniquement sur master

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Ollama Docker Image
        run: |
          docker build --no-cache -f Dockerfile.prod -t ghcr.io/${{ github.repository }}/ollama_miniapp-ollama:latest ./ollama
          docker push ghcr.io/${{ github.repository }}/ollama_miniapp-ollama:latest
