name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          cd backend && pytest && cd ..

  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest
    needs: python-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build --no-cache -t ollama_miniapp-backend ./backend

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: python-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build --no-cache -t ollama_miniapp-frontend ./frontend
