name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  python-tests:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          PYTHONPATH=./backend pytest backend/tests

  build-backend-develop:
    name: Build Backend for Develop
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/develop' # Condition pour `develop`

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image for Develop
        run: |
          docker build --no-cache -t ollama_miniapp-backend-develop ./backend

  build-frontend-develop:
    name: Build Frontend for Develop
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/develop' # Condition pour `develop`

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image for Develop
        run: |
          docker build --no-cache -t ollama_miniapp-frontend-develop ./frontend

  build-and-push-backend-master:
    name: Build and Push Backend for Master
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/master' # Condition pour `master`

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Backend Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/ollama_miniapp-backend:latest ./backend
          docker push ghcr.io/${{ github.repository }}/ollama_miniapp-backend:latest

  build-and-push-frontend-master:
    name: Build and Push Frontend for Master
    runs-on: ubuntu-latest
    needs: python-tests
    if: github.ref == 'refs/heads/master' # Condition pour `master`

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Frontend Docker Image
        run: |
          docker build --no-cache -t ghcr.io/${{ github.repository }}/ollama_miniapp-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository }}/ollama_miniapp-frontend:latest
